nav:
 - title: S-RAMP
   url: http://artificer.jboss.org
 - title: Design Time Governance
   url: /dtgov
 - title: Runtime Governance
   url: /rtgov
 - title: Get Involved
   url: /getinvolved
   subnav:
    - title: Contribute
      url: /getinvolved/contribute.html
    - title: Report a Bug
      url: /getinvolved/bugs.html
    - title: Chat
      url: /getinvolved/chat.html
    - title: User Forum
      url: https://community.jboss.org/en/overlord
    - title: Developer Forum
      url: https://community.jboss.org/en/overlord/dev
 - title: Follow Us
   url: /followus
   subnav:
    - title: Blog
      url: http://jboss-overlord.blogspot.com
    - title: "@OverlordSRAMP"
      url: https://twitter.com/ArtificerRepo
    - title: "@OverlordDTGov"
      url: https://twitter.com/OverlordDTGov
    - title: "@OverlordRTGov"
      url: https://twitter.com/OverlordRTGov
